<?php
// 12 de noviembre de 2017
// Lista de entidades de caracter HTML sacada de
// https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

$entidades_caracter = array(
  array("&quot;",     "quot",     "&amp;quot;",     "&amp;#x22;",   "HTML 2.0",  "comillas"),
  array("&amp;",      "amp",      "&amp;amp;",      "&amp;#x26;",   "HTML 2.0",  "et (en inglés, ampersand)"),
  array("&apos;",     "apos",     "&amp;apos;",     "&amp;#x27;",   "XHTML 1.0", "apóstrofo"),
  array("&lt;",       "lt",       "&amp;lt;",       "&amp;#x3C;",   "HTML 2.0",  "menor"),
  array("&gt;",       "gt",       "&amp;gt;",       "&amp;#x3E;",   "HTML 2.0",  "mayor"),
  array("&nbsp;",     "nbsp",     "&amp;nbsp;",     "&amp;#xA0;",   "HTML 3.2",  "espacio en blanco"),
  array("&iexcl;",    "iexcl",    "&amp;iexcl;",    "&amp;#xA1;",   "HTML 3.2",  "exclamación (apertura)"),
  array("&cent;",     "cent",     "&amp;cent;",     "&amp;#xA2;",   "HTML 3.2",  "céntimo"),
  array("&pound;",    "pound",    "&amp;pound;",    "&amp;#xA3;",   "HTML 3.2",  "libra"),
  array("&curren;",   "curren",   "&amp;curren;",   "&amp;#xA4;",   "HTML 3.2",  "moneda"),
  array("&yen;",      "yen",      "&amp;yen;",      "&amp;#xA5;",   "HTML 3.2",  "yen"),
  array("&brvbar;",   "brvbar",   "&amp;brvbar;",   "&amp;#xA6;",   "HTML 3.2",  "tubería"),
  array("&sect;",     "sect",     "&amp;sect;",     "&amp;#xA7;",   "HTML 3.2",  "sección"),
  array("&uml;",      "uml",      "&amp;uml;",      "&amp;#xA8;",   "HTML 3.2",  "diéresis"),
  array("&copy;",     "copy",     "&amp;copy;",     "&amp;#xA9;",   "HTML 3.2",  "copyright"),
  array("&ordf;",     "ordf",     "&amp;ordf;",     "&amp;#xAA;",   "HTML 3.2",  "ordinal femenino"),
  array("&laquo;",    "laquo",    "&amp;laquo;",    "&amp;#xAB;",   "HTML 3.2",  "apertura comillas angulares (guillemets)"),
  array("&not;",      "not",      "&amp;not;",      "&amp;#xAC;",   "HTML 3.2",  "negación"),
  array("&shy;",      "shy",      "&amp;shy;",      "&amp;#xAD;",   "HTML 3.2",  "guión de corte automático"),
  array("&reg;",      "reg",      "&amp;reg;",      "&amp;#xAE;",   "HTML 3.2",  "marca registrada"),
  array("&macr;",     "macr",     "&amp;macr;",     "&amp;#xAF;",   "HTML 3.2",  "acento macron"),
  array("&deg;",      "deg",      "&amp;deg;",      "&amp;#xB0;",   "HTML 3.2",  "grado"),
  array("&plusmn;",   "plusmn",   "&amp;plusmn;",   "&amp;#xB1;",   "HTML 3.2",  "más menos"),
  array("&sup2;",     "sup2",     "&amp;sup2;",     "&amp;#xB2;",   "HTML 3.2",  "al cuadrado"),
  array("&sup3;",     "sup3",     "&amp;sup3;",     "&amp;#xB3;",   "HTML 3.2",  "al cubo"),
  array("&acute;",    "acute",    "&amp;acute;",    "&amp;#xB4;",   "HTML 3.2",  "acento agudo"),
  array("&micro;",    "micro",    "&amp;micro;",    "&amp;#xB5;",   "HTML 3.2",  "micro"),
  array("&para;",     "para",     "&amp;para;",     "&amp;#xB6;",   "HTML 3.2",  "párrafo"),
  array("&middot;",   "middot",   "&amp;middot;",   "&amp;#xB7;",   "HTML 3.2",  "punto medio"),
  array("&cedil;",    "cedil",    "&amp;cedil;",    "&amp;#xB8;",   "HTML 3.2",  "cedilla"),
  array("&sup1;",     "sup1",     "&amp;sup1;",     "&amp;#xB9;",   "HTML 3.2",  "superíndice 1"),
  array("&ordm;",     "ordm",     "&amp;ordm;",     "&amp;#xBA;",   "HTML 3.2",  "ordinal masculino"),
  array("&raquo;",    "raquo",    "&amp;raquo;",    "&amp;#xBB;",   "HTML 3.2",  "cierre comillas angulares (guillemets)"),
  array("&frac14;",   "frac14",   "&amp;frac14;",   "&amp;#xBC;",   "HTML 3.2",  "fracción un cuarto"),
  array("&frac12;",   "frac12",   "&amp;frac12;",   "&amp;#xBD;",   "HTML 3.2",  "fracción un medio"),
  array("&frac34;",   "frac34",   "&amp;frac34;",   "&amp;#xBE;",   "HTML 3.2",  "fracción tres cuartos"),
  array("&iquest;",   "iquest",   "&amp;iquest;",   "&amp;#xBF;",   "HTML 3.2",  "interrogación (cierre)"),
  array("&Agrave;",   "Agrave",   "&amp;Agrave;",   "&amp;#xC0;",   "HTML 2.0",  "letra a mayúscula con acento grave"),
  array("&Aacute;",   "Aacute",   "&amp;Aacute;",   "&amp;#xC1;",   "HTML 2.0",  "letra a mayúscula con acento agudo"),
  array("&Acirc;",    "Acirc",    "&amp;Acirc;",    "&amp;#xC2;",   "HTML 2.0",  "letra a mayúscula con acento circunflejo"),
  array("&Atilde;",   "Atilde",   "&amp;Atilde;",   "&amp;#xC3;",   "HTML 2.0",  "letra a mayúscula con tilde"),
  array("&Auml;",     "Auml",     "&amp;Auml;",     "&amp;#xC4;",   "HTML 2.0",  "letra a mayúscula con diéresis"),
  array("&Aring;",    "Aring",    "&amp;Aring;",    "&amp;#xC5;",   "HTML 2.0",  "letra a mayúscula con anillo"),
  array("&AElig;",    "AElig",    "&amp;AElig;",    "&amp;#xC6;",   "HTML 2.0",  "ligadura ae mayúscula"),
  array("&Ccedil;",   "Ccedil",   "&amp;Ccedil;",   "&amp;#xC7;",   "HTML 2.0",  "letra c cedilla mayúscula"),
  array("&Egrave;",   "Egrave",   "&amp;Egrave;",   "&amp;#xC8;",   "HTML 2.0",  "letra e mayúscula con acento grave"),
  array("&Eacute;",   "Eacute",   "&amp;Eacute;",   "&amp;#xC9;",   "HTML 2.0",  "letra e mayúscula con acento agudo"),
  array("&Ecirc;",    "Ecirc",    "&amp;Ecirc;",    "&amp;#xCA;",   "HTML 2.0",  "letra e mayúscula con acento circunflejo"),
  array("&Euml;",     "Euml",     "&amp;Euml;",     "&amp;#xCB;",   "HTML 2.0",  "letra e mayúscula con diéresis"),
  array("&Igrave;",   "Igrave",   "&amp;Igrave;",   "&amp;#xCC;",   "HTML 2.0",  "letra i mayúscula con acento grave"),
  array("&Iacute;",   "Iacute",   "&amp;Iacute;",   "&amp;#xCD;",   "HTML 2.0",  "letra i mayúscula con acento agudo"),
  array("&Icirc;",    "Icirc",    "&amp;Icirc;",    "&amp;#xCE;",   "HTML 2.0",  "letra i mayúscula con acento circunflejo"),
  array("&Iuml;",     "Iuml",     "&amp;Iuml;",     "&amp;#xCF;",   "HTML 2.0",  "letra i mayúscula con diéresis"),
  array("&ETH;",      "ETH",      "&amp;ETH;",      "&amp;#xD0;",   "HTML 2.0",  "letra eth islandesa mayúscula"),
  array("&Ntilde;",   "Ntilde",   "&amp;Ntilde;",   "&amp;#xD1;",   "HTML 2.0",  "letra eñe mayúscula"),
  array("&Ograve;",   "Ograve",   "&amp;Ograve;",   "&amp;#xD2;",   "HTML 2.0",  "letra o mayúscula con acento grave"),
  array("&Oacute;",   "Oacute",   "&amp;Oacute;",   "&amp;#xD3;",   "HTML 2.0",  "letra o mayúscula con acento agudo"),
  array("&Ocirc;",    "Ocirc",    "&amp;Ocirc;",    "&amp;#xD4;",   "HTML 2.0",  "letra o mayúscula con acento circunflejo"),
  array("&Otilde;",   "Otilde",   "&amp;Otilde;",   "&amp;#xD5;",   "HTML 2.0",  "letra o mayúscula con tilde"),
  array("&Ouml;",     "Ouml",     "&amp;Ouml;",     "&amp;#xD6;",   "HTML 2.0",  "letra o mayúscula con diéresis"),
  array("&times;",    "times",    "&amp;times;",    "&amp;#xD7;",   "HTML 3.3",  "multiplicación"),
  array("&Oslash;",   "Oslash",   "&amp;Oslash;",   "&amp;#xD8;",   "HTML 2.0",  "letra o tachada mayúscula"),
  array("&Ugrave;",   "Ugrave",   "&amp;Ugrave;",   "&amp;#xD9;",   "HTML 2.0",  "letra u mayúscula con acento grave"),
  array("&Uacute;",   "Uacute",   "&amp;Uacute;",   "&amp;#xDA;",   "HTML 2.0",  "letra u mayúscula con acento agudo"),
  array("&Ucirc;",    "Ucirc",    "&amp;Ucirc;",    "&amp;#xDB;",   "HTML 2.0",  "letra u mayúscula con acento circunflejo"),
  array("&Uuml;",     "Uuml",     "&amp;Uuml;",     "&amp;#xDC;",   "HTML 2.0",  "letra u mayúscula con diéresis"),
  array("&Yacute;",   "Yacute",   "&amp;Yacute;",   "&amp;#xDD;",   "HTML 2.0",  "letra y mayúscula con acento agudo"),
  array("&THORN;",    "THORN",    "&amp;THORN;",    "&amp;#xDE;",   "HTML 2.0",  "letra thorn islandesa mayúscula"),
  array("&szlig;",    "szlig",    "&amp;szlig;",    "&amp;#xDF;",   "HTML 2.0",  "ligadura sz minúscula"),
  array("&agrave;",   "agrave",   "&amp;agrave;",   "&amp;#xE0;",   "HTML 2.0",  "letra a minúscula con acento grave"),
  array("&aacute;",   "aacute",   "&amp;aacute;",   "&amp;#xE1;",   "HTML 2.0",  "letra a minúscula con acento agudo"),
  array("&acirc;",    "acirc",    "&amp;acirc;",    "&amp;#xE2;",   "HTML 2.0",  "letra a minúscula con acento circunflejo"),
  array("&atilde;",   "atilde",   "&amp;atilde;",   "&amp;#xE3;",   "HTML 2.0",  "letra a minúscula con tilde"),
  array("&auml;",     "auml",     "&amp;auml;",     "&amp;#xE4;",   "HTML 2.0",  "letra a minúscula con diéresis"),
  array("&aring;",    "aring",    "&amp;aring;",    "&amp;#xE5;",   "HTML 2.0",  "letra a minúscula con anillo"),
  array("&aelig;",    "aelig",    "&amp;aelig;",    "&amp;#xE6;",   "HTML 2.0",  "ligadura ae minúscula"),
  array("&ccedil;",   "ccedil",   "&amp;ccedil;",   "&amp;#xE7;",   "HTML 2.0",  "letra c cedilla minúscula"),
  array("&egrave;",   "egrave",   "&amp;egrave;",   "&amp;#xE8;",   "HTML 2.0",  "letra e minúscula con acento grave"),
  array("&eacute;",   "eacute",   "&amp;eacute;",   "&amp;#xE9;",   "HTML 2.0",  "letra e minúscula con acento agudo"),
  array("&ecirc;",    "ecirc",    "&amp;ecirc;",    "&amp;#xEA;",   "HTML 2.0",  "letra e minúscula con acento circunflejo"),
  array("&euml;",     "euml",     "&amp;euml;",     "&amp;#xEB;",   "HTML 2.0",  "letra e minúscula con diéresis"),
  array("&igrave;",   "igrave",   "&amp;igrave;",   "&amp;#xEC;",   "HTML 2.0",  "letra i minúscula con acento grave"),
  array("&iacute;",   "iacute",   "&amp;iacute;",   "&amp;#xED;",   "HTML 2.0",  "letra i minúscula con acento agudo"),
  array("&icirc;",    "icirc",    "&amp;icirc;",    "&amp;#xEE;",   "HTML 2.0",  "letra i minúscula con acento circunflejo"),
  array("&iuml;",     "iuml",     "&amp;iuml;",     "&amp;#xEF;",   "HTML 2.0",  "letra i minúscula con diéresis"),
  array("&eth;",      "eth",      "&amp;eth;",      "&amp;#xF0;",   "HTML 2.0",  "letra eth islandesa minúscula"),
  array("&ntilde;",   "ntilde",   "&amp;ntilde;",   "&amp;#xF1;",   "HTML 2.0",  "letra eñe minúscula"),
  array("&ograve;",   "ograve",   "&amp;ograve;",   "&amp;#xF2;",   "HTML 2.0",  "letra o minúscula con acento grave"),
  array("&oacute;",   "oacute",   "&amp;oacute;",   "&amp;#xF3;",   "HTML 2.0",  "letra o minúscula con acento agudo"),
  array("&ocirc;",    "ocirc",    "&amp;ocirc;",    "&amp;#xF4;",   "HTML 2.0",  "letra o minúscula con acento circunflejo"),
  array("&otilde;",   "otilde",   "&amp;otilde;",   "&amp;#xF5;",   "HTML 2.0",  "letra o minúscula con tilde"),
  array("&ouml;",     "ouml",     "&amp;ouml;",     "&amp;#xF6;",   "HTML 2.0",  "letra o minúscula con diéresis"),
  array("&divide;",   "divide",   "&amp;divide;",   "&amp;#xF7;",   "HTML 3.2",  "división"),
  array("&oslash;",   "oslash",   "&amp;oslash;",   "&amp;#xF8;",   "HTML 2.0",  "letra o tachada minúscula"),
  array("&ugrave;",   "ugrave",   "&amp;ugrave;",   "&amp;#xF9;",   "HTML 2.0",  "letra u minúscula con acento grave"),
  array("&uacute;",   "uacute",   "&amp;uacute;",   "&amp;#xFA;",   "HTML 2.0",  "letra u minúscula con acento agudo"),
  array("&ucirc;",    "ucirc",    "&amp;ucirc;",    "&amp;#xFB;",   "HTML 2.0",  "letra u minúscula con acento circunflejo"),
  array("&uuml;",     "uuml",     "&amp;uuml;",     "&amp;#xFC;",   "HTML 2.0",  "letra u minúscula con diéresis"),
  array("&yacute;",   "yacute",   "&amp;yacute;",   "&amp;#xFD;",   "HTML 2.0",  "letra y minúscula con acento agudo"),
  array("&thorn;",    "thorn",    "&amp;thorn;",    "&amp;#xFE;",   "HTML 2.0",  "letra thorn islandesa minúscula"),
  array("&yuml;",     "yuml",     "&amp;yuml;",     "&amp;#xFF;",   "HTML 2.0",  "letra y minúscula con acento agudo"),
  array("&OElig;",    "OElig",    "&amp;OElig;",    "&amp;#x152;",  "HTML 4.0",  "ligadura oe mayúscula"),
  array("&oelig;",    "oelig",    "&amp;oelig;",    "&amp;#x153;",  "HTML 4.0",  "ligadura oe minúscula"),
  array("&Scaron;",   "Scaron",   "&amp;Scaron;",   "&amp;#x160;",  "HTML 4.0",  "letra s mayúscula con caron"),
  array("&scaron;",   "scaron",   "&amp;scaron;",   "&amp;#x161;",  "HTML 4.0",  "letra s minúscula con caron"),
  array("&Yuml;",     "Yuml",     "&amp;Yuml;",     "&amp;#x178;",  "HTML 4.0",  "letra y mayúscula con diéresis"),
  array("&fnof;",     "fnof",     "&amp;fnof;",     "&amp;#x192;",  "HTML 4.0",  "letra f cursiva minúscula (florín)"),
  array("&circ;",     "circ",     "&amp;circ;",     "&amp;#x2C6;",  "HTML 4.0",  "acento circunflejo"),
  array("&tilde;",    "tilde",    "&amp;tilde;",    "&amp;#x2DC;",  "HTML 4.0",  "tilde de la eñe"),
  array("&Alpha;",    "Alpha",    "&amp;Alpha;",    "&amp;#x391;",  "HTML 4.0",  "letra griega alfa mayúscula"),
  array("&Beta;",     "Beta",     "&amp;Beta;",     "&amp;#x392;",  "HTML 4.0",  "letra griega beta mayúscula"),
  array("&Gamma;",    "Gamma",    "&amp;Gamma;",    "&amp;#x393;",  "HTML 4.0",  "letra griega gamma mayúscula"),
  array("&Delta;",    "Delta",    "&amp;Delta;",    "&amp;#x394;",  "HTML 4.0",  "letra griega delta mayúscula"),
  array("&Epsilon;",  "Epsilon",  "&amp;Epsilon;",  "&amp;#x395;",  "HTML 4.0",  "letra griega epsilon mayúscula"),
  array("&Zeta;",     "Zeta",     "&amp;Zeta;",     "&amp;#x396;",  "HTML 4.0",  "letra griega zeta mayúscula"),
  array("&Eta;",      "Eta",      "&amp;Eta;",      "&amp;#x397;",  "HTML 4.0",  "letra griega eta mayúscula"),
  array("&Theta;",    "Theta",    "&amp;Theta;",    "&amp;#x398;",  "HTML 4.0",  "letra griega theta mayúscula"),
  array("&Iota;",     "Iota",     "&amp;Iota;",     "&amp;#x399;",  "HTML 4.0",  "letra griega iota mayúscula"),
  array("&Kappa;",    "Kappa",    "&amp;Kappa;",    "&amp;#x39A;",  "HTML 4.0",  "letra griega kappa mayúscula"),
  array("&Lambda;",   "Lambda",   "&amp;Lambda;",   "&amp;#x39B;",  "HTML 4.0",  "letra griega lambda mayúscula"),
  array("&Mu;",       "Mu",       "&amp;Mu;",       "&amp;#x39C;",  "HTML 4.0",  "letra griega mu mayúscula"),
  array("&Nu;",       "Nu",       "&amp;Nu;",       "&amp;#x39D;",  "HTML 4.0",  "letra griega nu mayúscula"),
  array("&Xi;",       "Xi",       "&amp;Xi;",       "&amp;#x39E;",  "HTML 4.0",  "letra griega xi mayúscula"),
  array("&Omicron;",  "Omicron",  "&amp;Omicron;",  "&amp;#x39F;",  "HTML 4.0",  "letra griega omicron mayúscula"),
  array("&Pi;",       "Pi",       "&amp;Pi;",       "&amp;#x3A0;",  "HTML 4.0",  "letra griega pi mayúscula"),
  array("&Rho;",      "Rho",      "&amp;Rho;",      "&amp;#x3A1;",  "HTML 4.0",  "letra griega rho mayúscula"),
  array("&Sigma;",    "Sigma",    "&amp;Sigma;",    "&amp;#x3A3;",  "HTML 4.0",  "letra griega sigma mayúscula"),
  array("&Tau;",      "Tau",      "&amp;Tau;",      "&amp;#x3A4;",  "HTML 4.0",  "letra griega tau mayúscula"),
  array("&Upsilon;",  "Upsilon",  "&amp;Upsilon;",  "&amp;#x3A5;",  "HTML 4.0",  "letra griega upsilon mayúscula"),
  array("&Phi;",      "Phi",      "&amp;Phi;",      "&amp;#x3A6;",  "HTML 4.0",  "letra griega phi mayúscula"),
  array("&Chi;",      "Chi",      "&amp;Chi;",      "&amp;#x3A7;",  "HTML 4.0",  "letra griega chi mayúscula"),
  array("&Psi;",      "Psi",      "&amp;Psi;",      "&amp;#x3A8;",  "HTML 4.0",  "letra griega psi mayúscula"),
  array("&Omega;",    "Omega",    "&amp;Omega;",    "&amp;#x3A9;",  "HTML 4.0",  "letra griega omega mayúscula"),
  array("&alpha;",    "alpha",    "&amp;alpha;",    "&amp;#x3B1;",  "HTML 4.0",  "letra griega alfa minúscula"),
  array("&beta;",     "beta",     "&amp;beta;",     "&amp;#x3B2;",  "HTML 4.0",  "letra griega beta minúscula"),
  array("&gamma;",    "gamma",    "&amp;gamma;",    "&amp;#x3B3;",  "HTML 4.0",  "letra griega gamma minúscula"),
  array("&delta;",    "delta",    "&amp;delta;",    "&amp;#x3B4;",  "HTML 4.0",  "letra griega delta minúscula"),
  array("&epsilon;",  "epsilon",  "&amp;epsilon;",  "&amp;#x3B5;",  "HTML 4.0",  "letra griega epsilon minúscula"),
  array("&zeta;",     "zeta",     "&amp;zeta;",     "&amp;#x3B6;",  "HTML 4.0",  "letra griega zeta minúscula"),
  array("&eta;",      "eta",      "&amp;eta;",      "&amp;#x3B7;",  "HTML 4.0",  "letra griega eta minúscula"),
  array("&theta;",    "theta",    "&amp;theta;",    "&amp;#x3B8;",  "HTML 4.0",  "letra griega theta minúscula"),
  array("&iota;",     "iota",     "&amp;iota;",     "&amp;#x3B9;",  "HTML 4.0",  "letra griega iota minúscula"),
  array("&kappa;",    "kappa",    "&amp;kappa;",    "&amp;#x3BA;",  "HTML 4.0",  "letra griega kappa minúscula"),
  array("&lambda;",   "lambda",   "&amp;lambda;",   "&amp;#x3BB;",  "HTML 4.0",  "letra griega lambda minúscula"),
  array("&mu;",       "mu",       "&amp;mu;",       "&amp;#x3BC;",  "HTML 4.0",  "letra griega mu minúscula"),
  array("&nu;",       "nu",       "&amp;nu;",       "&amp;#x3BD;",  "HTML 4.0",  "letra griega nu minúscula"),
  array("&xi;",       "xi",       "&amp;xi;",       "&amp;#x3BE;",  "HTML 4.0",  "letra griega xi minúscula"),
  array("&omicron;",  "omicron",  "&amp;omicron;",  "&amp;#x3BF;",  "HTML 4.0",  "letra griega omicron minúscula"),
  array("&pi;",       "pi",       "&amp;pi;",       "&amp;#x3C0;",  "HTML 4.0",  "letra griega pi minúscula"),
  array("&rho;",      "rho",      "&amp;rho;",      "&amp;#x3C1;",  "HTML 4.0",  "letra griega rho minúscula"),
  array("&sigmaf;",   "sigmaf",   "&amp;sigmaf;",   "&amp;#x3C2;",  "HTML 4.0",  "letra griega sigma final minúscula"),
  array("&sigma;",    "sigma",    "&amp;sigma;",    "&amp;#x3C3;",  "HTML 4.0",  "letra griega sigma minúscula"),
  array("&tau;",      "tau",      "&amp;tau;",      "&amp;#x3C4;",  "HTML 4.0",  "letra griega tau minúscula"),
  array("&upsilon;",  "upsilon",  "&amp;upsilon;",  "&amp;#x3C5;",  "HTML 4.0",  "letra griega upsilon minúscula"),
  array("&phi;",      "phi",      "&amp;phi;",      "&amp;#x3C6;",  "HTML 4.0",  "letra griega phi minúscula"),
  array("&chi;",      "chi",      "&amp;chi;",      "&amp;#x3C7;",  "HTML 4.0",  "letra griega chi minúscula"),
  array("&psi;",      "psi",      "&amp;psi;",      "&amp;#x3C8;",  "HTML 4.0",  "letra griega psi minúscula"),
  array("&omega;",    "omega",    "&amp;omega;",    "&amp;#x3C9;",  "HTML 4.0",  "letra griega omega minúscula"),
  array("&thetasym;", "thetasym", "&amp;thetasym;", "&amp;#x3D1;",  "HTML 4.0",  "letra griega theta cursiva minúscula"),
  array("&upsih;",    "upsih",    "&amp;upsih;",    "&amp;#x3D2;",  "HTML 4.0",  "letra griega upsilon con gancho mayúscula"),
  array("&piv;",      "piv",      "&amp;piv;",      "&amp;#x3D6;",  "HTML 4.0",  "letra griega omega pi minúscula"),
  array("&ensp;",     "ensp",     "&amp;ensp;",     "&amp;#x2002;", "HTML 4.0",  "espacio en (medio em)"),
  array("&emsp;",     "emsp",     "&amp;emsp;",     "&amp;#x2003;", "HTML 4.0",  "espacio em"),
  array("&thinsp;",   "thinsp",   "&amp;thinsp;",   "&amp;#x2009;", "HTML 4.0",  "espacio pequeño (1/5 em)"),
  array("&zwnj;",     "zwnj",     "&amp;zwnj;",     "&amp;#x200C;", "HTML 4.0",  "no-ensamblador de anchura cero"),
  array("&zwj;",      "zwj",      "&amp;zwj;",      "&amp;#x200D;", "HTML 4.0",  "ensamblador de anchura cero"),
  array("&lrm;",      "lrm",      "&amp;lrm;",      "&amp;#x200E;", "HTML 4.0",  "marca de izquierda a derecha"),
  array("&rlm;",      "rlm",      "&amp;rlm;",      "&amp;#x200F;", "HTML 4.0",  "marca de derecha a izquierda"),
  array("&ndash;",    "ndash",    "&amp;ndash;",    "&amp;#x2013;", "HTML 4.0",  "semirraya (guión medio)"),
  array("&mdash;",    "mdash",    "&amp;mdash;",    "&amp;#x2014;", "HTML 4.0",  "raya (guión largo)"),
  array("&lsquo;",    "lsquo",    "&amp;lsquo;",    "&amp;#x2018;", "HTML 4.0",  "comilla simple izquierda"),
  array("&rsquo;",    "rsquo",    "&amp;rsquo;",    "&amp;#x2019;", "HTML 4.0",  "comilla simple derecha"),
  array("&sbquo;",    "sbquo",    "&amp;sbquo;",    "&amp;#x201A;", "HTML 4.0",  "comilla simple inferior"),
  array("&ldquo;",    "ldquo",    "&amp;ldquo;",    "&amp;#x201C;", "HTML 4.0",  "comilla doble izquierda"),
  array("&rdquo;",    "rdquo",    "&amp;rdquo;",    "&amp;#x201D;", "HTML 4.0",  "comilla doble derecha"),
  array("&bdquo;",    "bdquo",    "&amp;bdquo;",    "&amp;#x201E;", "HTML 4.0",  "comilla doble inferior"),
  array("&dagger;",   "dagger",   "&amp;dagger;",   "&amp;#x2020;", "HTML 4.0",  "cruz"),
  array("&Dagger;",   "Dagger",   "&amp;Dagger;",   "&amp;#x2021;", "HTML 4.0",  "doble cruz"),
  array("&bull;",     "bull",     "&amp;bull;",     "&amp;#x2022;", "HTML 4.0",  "punto (de lista)"),
  array("&hellip;",   "hellip",   "&amp;hellip;",   "&amp;#x2026;", "HTML 4.0",  "elipsis"),
  array("&permil;",   "permil",   "&amp;permil;",   "&amp;#x2030;", "HTML 4.0",  "por mil"),
  array("&prime;",    "prime",    "&amp;prime;",    "&amp;#x2032;", "HTML 4.0",  "prima"),
  array("&Prime;",    "Prime",    "&amp;Prime;",    "&amp;#x2033;", "HTML 4.0",  "segunda (prima)"),
  array("&lsaquo;",   "lsaquo",   "&amp;lsaquo;",   "&amp;#x2039;", "HTML 4.0",  "comilla angular simple izquierda"),
  array("&rsaquo;",   "rsaquo",   "&amp;rsaquo;",   "&amp;#x203A;", "HTML 4.0",  "comilla simple angular derecha"),
  array("&oline;",    "oline",    "&amp;oline;",    "&amp;#x203E;", "HTML 4.0",  "guión alto"),
  array("&frasl;",    "frasl",    "&amp;frasl;",    "&amp;#x2044;", "HTML 4.0",  "barra de fracción"),
  array("&euro;",     "euro",     "&amp;euro;",     "&amp;#x20AC;", "HTML 4.0",  "euro"),
  array("&image;",    "image",    "&amp;image;",    "&amp;#x2111;", "HTML 4.0",  "parte imaginaria"),
  array("&weierp;",   "weierp",   "&amp;weierp;",   "&amp;#x2118;", "HTML 4.0",  "función elíptica de Weierstrass"),
  array("&real;",     "real",     "&amp;real;",     "&amp;#x211C;", "HTML 4.0",  "parte real"),
  array("&trade;",    "trade",    "&amp;trade;",    "&amp;#x2122;", "HTML 4.0",  "marca registrada"),
  array("&alefsym;",  "alefsym",  "&amp;alefsym;",  "&amp;#x2135;", "HTML 4.0",  "primer cardinal transfinito (numerable)"),
  array("&larr;",     "larr",     "&amp;larr;",     "&amp;#x2190;", "HTML 4.0",  "flecha hacia la izquierda"),
  array("&uarr;",     "uarr",     "&amp;uarr;",     "&amp;#x2191;", "HTML 4.0",  "flecha hacia arriba"),
  array("&rarr;",     "rarr",     "&amp;rarr;",     "&amp;#x2192;", "HTML 4.0",  "flecha hacia la derecha"),
  array("&darr;",     "darr",     "&amp;darr;",     "&amp;#x2193;", "HTML 4.0",  "flecha hacia abajo"),
  array("&harr;",     "harr",     "&amp;harr;",     "&amp;#x2194;", "HTML 4.0",  "flecha derecha izquierda (relación en notación z)"),
  array("&crarr;",    "crarr",    "&amp;crarr;",    "&amp;#x21B5;", "HTML 4.0",  "retorno de carro"),
  array("&lArr;",     "lArr",     "&amp;lArr;",     "&amp;#x21D0;", "HTML 4.0",  "flecha doble hacia la izquierda"),
  array("&uArr;",     "uArr",     "&amp;uArr;",     "&amp;#x21D1;", "HTML 4.0",  "flecha doble hacia arriba"),
  array("&rArr;",     "rArr",     "&amp;rArr;",     "&amp;#x21D2;", "HTML 4.0",  "flecha doble hacia la derecha"),
  array("&dArr;",     "dArr",     "&amp;dArr;",     "&amp;#x21D3;", "HTML 4.0",  "flecha doble hacia abajo"),
  array("&hArr;",     "hArr",     "&amp;hArr;",     "&amp;#x21D4;", "HTML 4.0",  "flecha doble derecha izquierda"),
  array("&forall;",   "forall",   "&amp;forall;",   "&amp;#x2200;", "HTML 4.0",  "para todo"),
  array("&part;",     "part",     "&amp;part;",     "&amp;#x2202;", "HTML 4.0",  "diferencial parcial"),
  array("&exist;",    "exist",    "&amp;exist;",    "&amp;#x2203;", "HTML 4.0",  "existe"),
  array("&empty;",    "empty",    "&amp;empty;",    "&amp;#x2205;", "HTML 4.0",  "conjunto vacío"),
  array("&nabla;",    "nabla",    "&amp;nabla;",    "&amp;#x2207;", "HTML 4.0",  "operador nabla"),
  array("&isin;",     "isin",     "&amp;isin;",     "&amp;#x2208;", "HTML 4.0",  "pertenece a"),
  array("&notin;",    "notin",    "&amp;notin;",    "&amp;#x2209;", "HTML 4.0",  "no pertenece a"),
  array("&ni;",       "ni",       "&amp;ni;",       "&amp;#x220B;", "HTML 4.0",  "contiene a"),
  array("&prod;",     "prod",     "&amp;prod;",     "&amp;#x220F;", "HTML 4.0",  "productorio"),
  array("&sum;",      "sum",      "&amp;sum;",      "&amp;#x2211;", "HTML 4.0",  "sumatorio"),
  array("&minus;",    "minus",    "&amp;minus;",    "&amp;#x2212;", "HTML 4.0",  "menos"),
  array("&lowast;",   "lowast",   "&amp;lowast;",   "&amp;#x2217;", "HTML 4.0",  "operador asterisco"),
  array("&radic;",    "radic",    "&amp;radic;",    "&amp;#x221A;", "HTML 4.0",  "raíz cuadrada"),
  array("&prop;",     "prop",     "&amp;prop;",     "&amp;#x221D;", "HTML 4.0",  "proporcional a"),
  array("&infin;",    "infin",    "&amp;infin;",    "&amp;#x221E;", "HTML 4.0",  "infinito"),
  array("&ang;",      "ang",      "&amp;ang;",      "&amp;#x2220;", "HTML 4.0",  "ángulo"),
  array("&and;",      "and",      "&amp;and;",      "&amp;#x2227;", "HTML 4.0",  "operador lógico y"),
  array("&or;",       "or",       "&amp;or;",       "&amp;#x2228;", "HTML 4.0",  "operador lógico o"),
  array("&cap;",      "cap",      "&amp;cap;",      "&amp;#x2229;", "HTML 4.0",  "intersección"),
  array("&cup;",      "cup",      "&amp;cup;",      "&amp;#x222A;", "HTML 4.0",  "unión"),
  array("&int;",      "int",      "&amp;int;",      "&amp;#x222B;", "HTML 4.0",  "integral"),
  array("&there4;",   "there4",   "&amp;there4;",   "&amp;#x2234;", "HTML 4.0",  "por lo tanto"),
  array("&sim;",      "sim",      "&amp;sim;",      "&amp;#x223C;", "HTML 4.0",  "operador tilde"),
  array("&cong;",     "cong",     "&amp;cong;",     "&amp;#x2245;", "HTML 4.0",  "aproximadamente igual a"),
  array("&asymp;",    "asymp",    "&amp;asymp;",    "&amp;#x2248;", "HTML 4.0",  "casi igual a"),
  array("&ne;",       "ne",       "&amp;ne;",       "&amp;#x2260;", "HTML 4.0",  "distinto de"),
  array("&equiv;",    "equiv",    "&amp;equiv;",    "&amp;#x2261;", "HTML 4.0",  "idéntico a"),
  array("&le;",       "le",       "&amp;le;",       "&amp;#x2264;", "HTML 4.0",  "inferior o igual"),
  array("&ge;",       "ge",       "&amp;ge;",       "&amp;#x2265;", "HTML 4.0",  "superior o igual"),
  array("&sub;",      "sub",      "&amp;sub;",      "&amp;#x2282;", "HTML 4.0",  "subconjunto de"),
  array("&sup;",      "sup",      "&amp;sup;",      "&amp;#x2283;", "HTML 4.0",  "superconjunto de"),
  array("&nsub;",     "nsub",     "&amp;nsub;",     "&amp;#x2284;", "HTML 4.0",  "no subconjunto de"),
  array("&sube;",     "sube",     "&amp;sube;",     "&amp;#x2286;", "HTML 4.0",  "subconjunto de o igual a"),
  array("&supe;",     "supe",     "&amp;supe;",     "&amp;#x2287;", "HTML 4.0",  "superconjunto de o igual a"),
  array("&oplus;",    "oplus",    "&amp;oplus;",    "&amp;#x2295;", "HTML 4.0",  "signo más rodeado por un círculo"),
  array("&otimes;",   "otimes",   "&amp;otimes;",   "&amp;#x2297;", "HTML 4.0",  "signo por rodeado por un círculo"),
  array("&perp;",     "perp",     "&amp;perp;",     "&amp;#x22A5;", "HTML 4.0",  "perpendicular"),
  array("&sdot;",     "sdot",     "&amp;sdot;",     "&amp;#x22C5;", "HTML 4.0",  "operador punto"),
  array("&lceil;",    "lceil",    "&amp;lceil;",    "&amp;#x2308;", "HTML 4.0",  "corchete superior izquierdo"),
  array("&rceil;",    "rceil",    "&amp;rceil;",    "&amp;#x2309;", "HTML 4.0",  "corchete superior derecho"),
  array("&lfloor;",   "lfloor",   "&amp;lfloor;",   "&amp;#x230A;", "HTML 4.0",  "corchete inferior izquierdo"),
  array("&rfloor;",   "rfloor",   "&amp;rfloor;",   "&amp;#x230B;", "HTML 4.0",  "corchete inferior derecho"),
  array("&lang;",     "lang",     "&amp;lang;",     "&amp;#x2329;", "HTML 4.0",  "corchete angular izquierdo"),
  array("&rang;",     "rang",     "&amp;rang;",     "&amp;#x232A;", "HTML 4.0",  "corchete angular derecho"),
  array("&loz;",      "loz",      "&amp;loz;",      "&amp;#x25CA;", "HTML 4.0",  "rombo"),
  array("&spades;",   "spades",   "&amp;spades;",   "&amp;#x2660;", "HTML 4.0",  "picas"),
  array("&clubs;",    "clubs",    "&amp;clubs;",    "&amp;#x2663;", "HTML 4.0",  "tréboles"),
  array("&hearts;",   "hearts",   "&amp;hearts;",   "&amp;#x2665;", "HTML 4.0",  "corazones"),
  array("&diams;",    "diams",    "&amp;diams;",    "&amp;#x2666;", "HTML 4.0",  "rombos"),
 );
